export const GET_POKEMONS_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMON_ERROR';

export const GET_POKEMON_BY_ID_REQUEST = 'GET_POKEMON_BY_ID_REQUEST';
export const GET_POKEMON_BY_ID_SUCCESS = 'GET_POKEMON_BY_ID_SUCCESS';
export const GET_POKEMON_BY_ID_ERROR = 'GET_POKEMON_BY_ID_ERROR';

export const UPDATE_POKEMON_BY_ID_REQUEST = 'UPDATE_POKEMON_BY_ID_REQUEST';
export const UPDATE_POKEMON_BY_ID_SUCCESS = 'UPDATE_POKEMON_BY_ID_SUCCESS';
export const UPDATE_POKEMON_BY_ID_ERROR = 'UPDATE_POKEMON_BY_ID_ERROR';

export const UPDATE_COUNTER = 'UPDATE_COUNTER';

